### ISSUE TITLE
baypass2betascan2.py output file running in BetaScan.py reported error 

### ISSUE THREAD

**Issue by Huangglian** [TheDBStern/NEE2020#1]
Dear David B. Stern:

When I use my data following your scripts to calculate the B2, the baypass2betascan2.py output file running in BetaScan.py reported error. 
First, I got multipopulation BayPass format output file by using poolfstat and awk command to , like:

scaffold1 3186 27 101 14 125 6 84 28 90
scaffold1 3188 98 28 119 14 84 6 93 28
scaffold1 3216 114 27 117 16 93 12 94 31

then run baypass2betascan2.py and got the pop1 output like:

3109    25      191
3131    27      199
3154    225     225
3161    36      234
3228    41      267

When I run "python2 BetaScan2.py-B2-DivTime 2-i sca100-o sca100_beta", I get an error report:
Traceback (most recent call last):
 File "BetaScan2.py",line 618,in <module>
 main ()
 File "BetaScan2.py",line 607,in main
 output.write (str (loc) + "\ t" + str (round (B, 6)) + "\ n") # Remove thetas
TypeError: a float is required

And I found some beta2 value is very high in the output file, like this:

94127   -2.228801
94443   1.172018
94854   -1.228611
97432   -4.490486
......
367974  7294.856581
368006  6096.10307
368059  6699.382283
368111  6960.638325

 I have no idea why the value suddently change so high, and I wonder if you have any suggestions to solve these problem? 

Thank you for your help,

Guilian Huang

**Comment by TheDBStern** [comment]
Hello Guilian,

The _baypass2betascan2.py_ script requires that you have 2 reciprocally monophyletic groups of populations, so that they can be used as each others "outgroup" in order to polarize SNP frequencies and call substitutions. Does your dataset fit that requirement? If not, I would advise using the _baypass2betascan.py_ script instead and using the folded version of BetaScan 1. 

Otherwise, the issue may be with your BetaScan2 command. You may need to specify a different window size or minimum SNP frequency.

What does your input file look like around those sites with very high beta scores?

-David

**Comment by Huangglian** [comment]
Dear David,

Thank you so much for your reply. Actually, our data include two different ecotype populations from the same species, there are few polarized SNPs and call substitutions. About those sites with very high beta scores, which look normal compare with other sites, like: 
       Input                                output         
340718  25      268         340718  1.139921    
340870  246     246        340886  0.406094
340886  52      243         341043  -0.703357
341016  264     264        341255  -1.737664
341043  220     248        341366  -1.158691
341255  112     248        341514  3997.273195
341366  80      228         342070  9092.164337
341478  278     278        342131  9775.129148
341514  91      280         342385  6106.313382
341549  286     286        342424  5248.457478
341560  294     294
341564  295     295
342039  196     196
342070  13      210
342131  11      196
342385  53      259
342424  65      258

Anyway, I will try to specify BetaScan2 command, thanks again.

Sincerely,

Guilian
